### ISSUE TITLE
Remove all non-default pattern engines once stable

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/edition-node-gulp#1]
Alter `getSupportedTemplateExtensions()` to look for `node_modules/patternengine-node-*` instead of its current mechanism

**Comment by bmuenzenmeyer** [comment]
now managed in core

**Comment by geoffp** [comment]
While this is true -- I just found template renderers (rather than engines) hanging around in the edition! This issue seems close enough to me. Removing them.
