### ISSUE TITLE
package.json missing dependency

### ISSUE THREAD

**Issue by ninjasort** [pattern-lab/edition-node-gulp#100]
Not sure what I'm missing here but the readme details the mustache templates `patternengine-node-mustache` included but they are not listed as a dependency [here](https://github.com/pattern-lab/edition-node-gulp/blob/master/package.json#L5). Any idea how the mustache templates are being included?

**Comment by bmuenzenmeyer** [comment]
Hi @cameronroe just seeing this now, sorry. In the current builds, we include `patternengine-node-mustache` as a dependency of core `patternlab-node` for simplicity's sake. 

This is slated to change in 3.0. Thanks for nudging me on this oddity.

**Comment by ninjasort** [comment]
Cool! No worries.

**Comment by bmuenzenmeyer** [comment]
Re-added as part of https://github.com/pattern-lab/patternlab-node/commit/d2f346d43532bdc939d476cb26e2a821f7a982f7 - not the grand vision I want yet, but included for convenience's sake.
