### ISSUE TITLE
Link not working with pattern parameters in action

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/edition-node-gulp#102]
##### Expected Behavior
Using link in JSON, such as: 

```
{
    "url": "link.pages-homepage"
}
```

Should render links correctly when pattern parameters are in place, such as:

```
{{> organisms-header(styleModifier: "c-header--vertical") }}
```

##### Actual Behavior

The `{{ url }}` field is replaced with `link.pages-homepage`, resulting in a link that looks like `<a href="link.pages-homepage">`. This returns a 404 page when clicked. 

##### Steps to Reproduce
1. Create a `link` to another Pattern Lab page in JSON.
2. Include a component that includes the desired link while passing in pattern parameters. 
3. Click the link

**Comment by bmuenzenmeyer** [comment]
in an unlikely workaround scenario, does 

```
{{> organisms-header:c-header--vertical }}
```

work instead? 

(pattern parametes are buggy - i wonder if using only the stylemodier syntax would work) http://patternlab.io/docs/pattern-stylemodifier.html

**Comment by frostyweather** [comment]
@bmuenzenmeyer That seemed to do the trick workaround wise. 

Since we were naming the `styleModifier` `headerStyleModifier`, we used a different workaround that wrapped the header in `{{# styleguideHeader }}{{/ styleGuideHeader }}` and used the JSON file to change the modifier:
```
"styleguideHeader" : {
        "headerStyleModifier" : "c-header--vertical"
 }
```

**Comment by bmuenzenmeyer** [comment]
good. sorry for the inconvenience. after some client work finishes up i plan to re-focus again more on issues such as these.

as we've always maintained.... the more you use pattern parameters, the more trouble you get into 😱

**Comment by frostyweather** [comment]
@bmuenzenmeyer No worries, just glad there's a workaround for now. Thanks!

**Comment by bmuenzenmeyer** [comment]
I've fixed this, and perhaps found the source of many other bugs due to an order of operations problem with core. Look for an official release soon.

**Comment by bmuenzenmeyer** [comment]
@bradfrost @frostyweather 
this is fixed with https://github.com/pattern-lab/patternlab-node/releases/tag/v2.9.2

`npm update`
