### ISSUE TITLE
Error: Cannot GET /

### ISSUE THREAD

**Issue by ryanaltvater** [pattern-lab/edition-node-gulp#115]
After running `gulp patternlab:version`, I am using Pattern Lab Node- Gulp Edition `v3.0.0-alpha.5` on `Mac` as-is right out of the box without any modifications.

##### Expected Behavior
Run `gulp patternlab:serve`

![screen shot 2017-12-18 at 1 45 29 pm](https://user-images.githubusercontent.com/1336787/34122262-d37d5efc-e3f9-11e7-95cf-61c214adcc96.png)

##### Actual Behavior
Run `gulp patternlab:serve`

![screen shot 2017-12-18 at 1 45 07 pm](https://user-images.githubusercontent.com/1336787/34122281-e5d7f116-e3f9-11e7-912a-4be2e738b857.png)

##### Steps to Reproduce
1. Run `gulp patternlab:serve`
2. Browser launches screenshot from "Actual Behavior"
3. Refresh browser tab
4. Browser shows screenshot from "Expected Behavior"

**Comment by bmuenzenmeyer** [comment]
I think I've resolved this with the latest (unreleased) alpha.

**Comment by rvnewolf** [comment]
I just created a fresh install and I am having the exact same issue as @ryanaltvater described above. Version details below.

```
"version": "2.0.0-alpha.1",
  "main": "gulpfile.js",
  "dependencies": {
    "@pattern-lab/patternengine-node-mustache": "^2.0.0-alpha.1",
    "@pattern-lab/patternlab-node": "^3.0.0-alpha.5",
    "@pattern-lab/styleguidekit-assets-default": "^4.0.0-alpha.2",
    "@pattern-lab/styleguidekit-mustache-default": "^4.0.0-alpha.1",
    "gulp": "^3.9.1",
    "minimist": "^1.2.0"
  }
```

**Comment by Roralee** [comment]
I am getting the same issue. Nothing appearing in the terminal to indicate that there is a problem.
`AJOHANSEMAC-HO:patternlibrary ajohanse$ npm install starterkit-mustache-demo
- starterkit-mustache-demo@4.0.2
updated 1 package in 3.106s
AJOHANSEMAC-HO:patternlibrary ajohanse$ npm install
up to date in 2.103s
AJOHANSEMAC-HO:patternlibrary ajohanse$ gulp patternlab:serve
Pattern Lab Node v3.0.0-alpha.5
Pattern Engine mustache: good to go
[21:36:12] Using gulpfile ~/Sites/patternlibrary/gulpfile.js
[21:36:12] Starting 'patternlab:serve'...
[21:36:12] Finished 'patternlab:serve' after 11 ms
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/node_modules/@pattern-lab/styleguidekit-assets-default/dist for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/js for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/images for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/fonts for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/css for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/_data/* for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/_meta/* for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/_patterns/**/*.json for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/_patterns/**/*.yml for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/_patterns/**/*.yaml for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/_patterns/**/*.md for changes
Pattern Lab is watching /Users/ajohanse/Sites/patternlibrary/source/_patterns/**/*.mustache for changes
Pattern Lab is being served from http://127.0.0.1:3000`

`{
  "name": "@pattern-lab/edition-node-gulp",
  "description": "The gulp wrapper around patternlab-node core, providing tasks to interact with the core library and move supporting frontend assets.",
  "version": "2.0.0-alpha.1",
  "main": "gulpfile.js",
  "dependencies": {
    "@pattern-lab/patternengine-node-mustache": "^2.0.0-alpha.1",
    "@pattern-lab/patternlab-node": "^3.0.0-alpha.5",
    "@pattern-lab/styleguidekit-assets-default": "^4.0.0-alpha.2",
    "@pattern-lab/styleguidekit-mustache-default": "^4.0.0-alpha.1",
    "gulp": "^3.9.1",
    "minimist": "^1.2.0",
    "starterkit-mustache-demo": "^4.0.2"
  },
  "keywords": [
    "Pattern Lab",
    "Atomic Web Design",
    "Node",
    "Gulp",
    "Javascript"
  ],
  "repository": {
    "type": "git",
    "url": "git://github.com/pattern-lab/edition-node-gulp.git"
  },
  "bugs": "https://github.com/pattern-lab/edition-node-gulp/issues",
  "author": "Brian Muenzenmeyer",
  "scripts": {
    "gulp": "gulp -- "
  },
  "license": "MIT",
  "engines": {
    "node": ">=6.0"
  }
}
`

<img width="455" alt="mac-osx-chrome-gulp" src="https://user-images.githubusercontent.com/6432414/34857363-5845236e-f718-11e7-9cc0-bd9845aa167d.png">

**Comment by bmuenzenmeyer** [comment]
Please upgrade `@pattern-lab/patternlab-node` to `3.0.0-alpha.6` and report back findings

**Comment by ryanaltvater** [comment]
I apologize for such a late response to this thread. I just ran version ```3.0.0-alpha.8``` and ```gulp patternlab:serve``` did launch the "expected" behavior identified above.

**Comment by Roralee** [comment]
Apologies, I just noticed this. I had switched over to the webpack version of patternlab since I was able to get it up and running in about 15 min.

I did an https clone of node-gulp then ran `npm install && npm run bootstrap`. Here's as far as it went:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/lib/node_modules/node/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'patternlab:serve' ]
2 info using npm@5.8.0
3 info using node@v8.3.0
4 verbose stack Error: missing script: patternlab:serve
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:18)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
5 verbose cwd /Users/ajohanse/Sites/patternlab
6 verbose Darwin 16.7.0
7 verbose argv "/usr/local/lib/node_modules/node/bin/node" "/usr/local/bin/npm" "run" "patternlab:serve"
8 verbose node v8.3.0
9 verbose npm  v5.8.0
10 error missing script: patternlab:serve
11 verbose exit [ 1, true ]
```

**Comment by bmuenzenmeyer** [comment]
@Roralee there's a couple things going on here



> I had switched over to the webpack version of patternlab

the webpack version is not tracking PL Node 3.0 alpha yet....

> I did an https clone of node-gulp then ran npm install && npm run bootstrap

`node-gulp` is not a repository I am aware of. I am being nitpicky with what you wrote because we have lots of different repos floating around, including this one, which will be obsoleted and archived soon!

`npm run bootstrap` is a command that one would only run if they had cloned [`patternlab-node`](https://github.com/pattern-lab/patternlab-node) (the new monorepo) and were bootstrapping all the repos together using Lerna. This is taken from the [contribution guidelines](https://github.com/pattern-lab/patternlab-node/blob/master/.github/CONTRIBUTING.md#developing-locally) which do not cover the repo this current issue covers anymore. 

There's a lot of moving parts in play right now - so it's hard for me to understand where to point you next. Are you trying to use a stable version of Pattern Lab / Webpack Edition, or an Alpha version?

**Comment by Roralee** [comment]
I'm running fine on Pattern Lab/Webpack. I had switched to it shortly after my original post re: Pattern Lab/Gulp issue. 

I came up w/ the `node-gulp...boostrap` based on where the documentation was sending me in order to set up a new Pattern Lab/Gulp instance. It's a little disjointed but as you say, you're in flux right now.

**Comment by bmuenzenmeyer** [comment]
oh i missed the OP from you - too many notifications! 

lemme know if  you aren't alright sitting tight with Webpack until the dust settles more

**Comment by Roralee** [comment]
I'm good working w/ Webpack for now. Now worries ;-)

**Comment by mentizm** [comment]
Hi same Problem here.

I run:
`git clone https://github.com/Comcast/patternlab-edition-node-webpack.git`
`npm install //no errors`
`npm run patternlab:build //no errors`
`npm run patternlab:serve //no errors`

New Window was open with: cannot GET /error

Solution:

- I stopped and closed my Docker
- run `killall node`
- and again run `npm run patternlab:serve`

Everything works fine ;-)
