### ISSUE TITLE
no such file or directory, rename patternengine-node-underscore

### ISSUE THREAD

**Issue by Isabellle** [pattern-lab/edition-node-gulp#123]
I am using Pattern Lab Node- Gulp latest `2.0.0-alpha.2` edition on `Windows`.

##### Expected Behavior

Npm to install all packages

##### Actual Behavior
```
npm ERR! path C:\Users\xx\Documents\xx\patternlab\node_modules\.staging\@pattern-lab\patternlab-node-3246eafa\node_modules\@pattern-lab\patternengine-node-underscore
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\xx\Documents\xx\patternlab\node_modules\.staging\@pattern-lab\patternlab-node-3246eafa\node_modules\@pattern-lab\patternengine-node-underscore' -> 'C:\Users\xx\Documents\xx\patternlab\node_modules\.staging\@pattern-lab\patternengine-node-underscore-810c51a0'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xx\AppData\Roaming\npm-cache\_logs\2018-02-19T08_19_55_773Z-debug.log
```

##### Steps to Reproduce

npm install

**Comment by elemk0vv** [comment]
There we go:

git clone https://github.com/pattern-lab/edition-node-gulp.git
cd edition-node-gulp
rm -rf package-lock.json
npm cache verify
npm cache clear -- force
[ npm install ] // useless, sorry 

gulp patternlab:build
gulp patternlab:serve

**Comment by bmuenzenmeyer** [comment]
@Isabellle thanks for the report and @elemk0vv thanks for the workaround

To me this is a symptom of a bad release - https://github.com/pattern-lab/edition-node-gulp/releases/tag/v2.0.0-alpha.3 should be cleaner

**Comment by Isabellle** [comment]
Thanks for your feedback @bmuenzenmeyer  (and big thanks for this awesome initiative and for making workflows between teams much much better)
