### ISSUE TITLE
Styleguide Tools > Code

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/edition-node-gulp#13]

**Comment by bmuenzenmeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/298435/15779754/cb95c74e-2963-11e6-9023-29173aab9fe1.png)

working thanks to a chat with Dave

**Comment by bradfrost** [comment]
Neat!

---

Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

On Fri, Jun 3, 2016 at 9:18 AM, Brian Muenzenmeyer <notifications@github.com
