### ISSUE TITLE
Pattern Info: HTML tab - output / formatting 

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/edition-node-gulp#5]

**Comment by bmuenzenmeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/298435/14450281/a40c668c-0042-11e6-9f7a-7ea7fe160b3a.png)

edition-php-development also does not have this done yet. Was hoping to better understand how this could be styled better, but will defer to @dmolsen 

Plenty of other work to do for now!

**Comment by dmolsen** [comment]
This isn't hooked up yet and it's what I'm working on this week. Brad had done some new layout and styling obviously. My work is a rewrite of the code and annotation related JS to better support plugins in the PHP edition.

**Comment by bmuenzenmeyer** [comment]
Good to hear, and what I was expecting given some recent discussions - sorry to spam you, prompting a response.   Is it safe to say that the internals of the the lineage, annotations and comments are fairly stable then?  

**Edit** I reread you comment and now think that I should probably hold off until the dust settles a bit.

**Comment by dmolsen** [comment]
The PHP code is basically solid. The front end obviously not so much but I think the only big issue I was hoping to tackle there was standardizing the panels.

**Comment by bradfrost** [comment]
@dmolsen let me know when you have something in there and I can start styling those panels.

**Comment by bmuenzenmeyer** [comment]
This is now working off of the new `feature-panels` branch of styleguidekit-assets-default
