### ISSUE TITLE
patternlab:serve not working on fresh install

### ISSUE THREAD

**Issue by BrenMurrell** [pattern-lab/edition-node-gulp#51]
I am using Pattern Lab Node edition-node-gulp `v1.2.1` on `Windows`
##### Expected Behavior

Running `gulp patternlab:serve` compiles patternlab and spins up a local server on port :3000
##### Actual Behavior

Get the following error:

```
 Using gulpfile c:\dev\_tests\plne\gulpfile.js
C:\Users\bren.murrell\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\bren.murrell\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:19
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```
##### Steps to Reproduce
1. install repo by running `git clone https://github.com/pattern-lab/edition-node-gulp .` in empty directory
2. run `npm install`
3. run `gulp patternlab:serve`
##### Environment
- Node v4.4.5 (64 bit)
- Gulp v4.0.0-alpha.2
- Gulp CLI version 3.9.1

**Comment by BrenMurrell** [comment]
As a follow up, generally I'm running tasks from the command line, but I usually code in Visual Studio code. Most other gulp-based projects I run, I can press `CTRL + P` and type `task` to get a list of available tasks. VS Code errors out in this project.  Error below (appears to be the same error, so hope this helps!)

```
C:\Users\bren.murrell\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:147
  console.log(Object.keys(localGulp.tasks)
                     ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at logTasksSimple (C:\Users\bren.murrell\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:147:22)
    at C:\Users\bren.murrell\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:124:14
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by bmuenzenmeyer** [comment]
@BrenMurrell your gulp CLI version is strange. [Their package.json](https://github.com/gulpjs/gulp-cli/blob/master/package.json) only reports up to 1.2.1, which I have confirmed I am on and is working.

If you follow the steps [on the wiki regarding upgrading gulp](https://github.com/pattern-lab/edition-node-gulp/wiki/Updating-to-Gulp-4) do you get the same results?

**Comment by BrenMurrell** [comment]
AHAH! Thank you sooooo much.  This set me right. Thanks again for _all_ of your help!

**Comment by bmuenzenmeyer** [comment]
Happy Pattern Labbing!
