### ISSUE TITLE
Cache Buster not outputting.

### ISSUE THREAD

**Issue by brianjhanson** [pattern-lab/edition-node-gulp#56]
I am using Pattern Lab Node `v6.2.0` on `Mac`, using the `gulp` configuration.
##### Expected Behavior

`{{ cacheBuster }}` should output the current time in the head and foot mustache templates.
##### Actual Behavior

`{{ cacheBuster }}` doesn't output anything.
##### Steps to Reproduce

Download pre-built gulp edition and get it running, make sure the `cacheBust` setting is set to `true`. Nothing is output behind the `?` of the stylesheets in the head. 

It seems like this variable isn't getting provided to the actual template, it's working properly in `{{{ patternLabHead }}}` section.

**Comment by bmuenzenmeyer** [comment]
Confirmed, thanks for finding this

**Comment by bmuenzenmeyer** [comment]
https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/patternlab.js#L299

**Comment by brianjhanson** [comment]
Tried to fix this guy, figured out that the buster is outputting correctly on single pattern pages just not on the "all" page. Haven't quite figured out why that would be yet though.

**Comment by bmuenzenmeyer** [comment]
Fixed this by adding `cacheBuster: patternlab.cacheBuster` to https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/ui_builder.js#L452 

will patch tonight unless someone else gets to it

**Comment by bmuenzenmeyer** [comment]
@brianjhanson could you change your package.json `patternlab-node` version to:

`"patternlab-node": "pattern-lab/patternlab-node#dev"`

and retest?

**Comment by brianjhanson** [comment]
🎉 seems to be working over here.
