### ISSUE TITLE
Gulp build ignores .scss files

### ISSUE THREAD

**Issue by philapple** [pattern-lab/edition-node-gulp#57]
I am using Pattern Lab Node v1.2.3 on Mac, using the gulp configuration.
##### Expected Behavior

I would expect everything inside source/css (the style.scss file and everything inside the /scss folder) to get compiled into style.css
##### Actual Behavior

Nothing gets compiled. I understand this seems to be intentional but:
1. Why do you distribute and include the scss files if they do not get compiled?
2. How can I change this behaviour so that the gulp build will consider the scss files?

Shouldn't the style of my components (atoms, molecules, etc) be described in the scss files that are being ignored by the build?
##### Steps to Reproduce
1. Added some variables and classes for my atoms in source/css/scss/base/_text.scss
2. Tried to apply this new classess to an atom in my pattern library
3. gulp patternlab:serve
4. No changes

**Comment by bmuenzenmeyer** [comment]
Hello @philapple -  thanks for the issue report. I understand where you are coming from, and have even supported scss compilation in past versions of Pattern Lab Node, but [ultimately removed direct support](https://github.com/pattern-lab/patternlab-node/releases/tag/v1.1.0) as not core functionality.

Why? Well, maintaining this step in the build chain is a decision best left to users. Shipping with scss is convenient for many reasons, but forcing people to use this preprocessor goes against the tool agnostic mantra you can find on [http://patternlab.io/](http://patternlab.io/).

What about [webpack](https://github.com/pattern-lab/patternlab-node/issues/325)? What about postcss? It just comes down to limited bandwidth and reducing lock-in for consumers. 

Editions are meant to be extended and wholesale re-purposed to a user's needs. [This issue also exists](https://github.com/pattern-lab/edition-node-gulp/issues/34) to make installation a bit more streamlined, versus shipping with a limited set of files inside `source/`. It probably wouldn't hurt to remove the scss files for clarity's sake.

One final note - at a recent workshop I helped an attendee add scss compilation to his edition with about 4 minutes of over-the-should encouragement. That's the beauty of the gulp/grunt task system, Pattern Lab is just another task to fit into whatever workflow you already have. I have designs to write a blog post on how to do this - but haven't found the time yet.

Thanks for your thoughts, and I hope you understand the reasoning I've laid out above.

**Comment by ronalson** [comment]
Hey @bmuenzenmeyer, sorry for bring this issue back to life, but I'm having a hard time understanding how I can proper configure PatternLab so it handles a SCSS compilation workflow.

I've followed those two tutorials ([yours](http://www.brianmuenzenmeyer.com/adding-common-gulp-tasks-to-pattern-lab-node), [other](https://medium.com/buildit/taking-patternlab-modularity-to-the-next-level-774b06c8bf6f)) pointing for changes on the gulpfile.js for the edition-node-gulp. However the  gulpfile.js shipped with the actual edition differs in many ways from the file mentioned on the articles.

[Actual gulpfile.js](https://github.com/pattern-lab/edition-node-gulp/blob/master/gulpfile.js) for commit efbb1f0 on 20 Nov 2017

[gulpfile gist example](https://gist.github.com/bmuenzenmeyer/7a6ec54dc1ea720a61497a75ea88e3b4) mentioned in your tutorial

I did some experiments trying to add / call gulp tasks inside the promises of server() and patternlab:server, but I don't have much experience working with this kind of configuration. Also, I couldn't find any reference for this type of overrides configuration on patternlab docs. Is there any material you can point me to?

**Comment by bmuenzenmeyer** [comment]
Those articles pertain to edition 1.X behavior so you should target a 1.X tag. I suggest https://github.com/pattern-lab/edition-node-gulp/releases/tag/v1.3.4 

The soon to be released newer version of Pattern Lab Node Core and Editions internalize the movement of files from source to public. What users do with files before or after that period is up to them. In the run up to release I need to create another example of how to do this (I do it for non-gulp [here](https://github.com/bmuenzenmeyer/patternlab-node-3.0-demo-integration)) and probably update that article - but the exercise is really left to userland. Whatever you want to do with SCSS, go for it, Pattern Lab is only concerned with moving files from the configured `source/css` location to the configured `public/css` location. This is the more sustainable approach that chasing the tail of the entire web design community's workflow of the moment. Hope that makes sense. I know it can be made more clear.

**Comment by ronalson** [comment]
Thanks for the quick answer, Brian. I was too immerse into the problem to think about checking out to an older version. I manage to download the mentioned release and configure the SCSS compilation. Now it's working just fine.

About the clearness of the documentation, for sure it is a real issue - I can say: especially for newcomers like me. Many times while setting up PatternLab I came across incompatible examples and command snippets. I don't think I can contribute a lot right now, but I can volunteer myself to beginner-proof-test the next docs. :)

To finish, I would like to say that the PatternLab is amazing! I think it will improve big time my workflow. I'm trying to follow a more pattern-driven development workflow and there is no match for PL!

**Comment by gogs85** [comment]
Hi, I would like to use with webpack but also to use scss. How to config to work?
`    test:/\.(s*)css$/,
          use:['style-loader','css-loader', 'sass-loader']`
