### ISSUE TITLE
Most Form Elements Refuse Focus

### ISSUE THREAD

**Issue by NathanFrund** [pattern-lab/edition-node-gulp#58]
I am using Pattern Lab Node `v1.2.3` on `Mac`, using the `gulp` configuration.
##### Expected Behavior

When clicking a form element (text input, select, textarea) it should receive and keep focus. 
##### Actual Behavior

When clicking on a form element, focus is removed, preventing interaction. Radio button behavior appears normal, as I am able to change a radio button's selected option.
##### Steps to Reproduce

I started with a fresh install by downloading the release zip.

If I comment out {{{ patternLabFoot }}} in _01.foot.mustache, I can interact with the form element, enter values, etc. But obviously, I lose PatternLab functionality.

**Comment by bmuenzenmeyer** [comment]
Hi @NathanFrund 

This was found and fixed last week, but it's possible I messed something up in consuming the fix.

Can you run `npm update` first and then check which version of `styleguidekit-assets-default` is in your `node_modules`? You should have `3.1.1`

**Comment by NathanFrund** [comment]
@bmuenzenmeyer that did it!

Thank you very much.

**Comment by bmuenzenmeyer** [comment]
Cheers!
