### ISSUE TITLE
twig pattern engine

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-node-gulp#60]
Is there currently a way to use the node version of Pattern Lab with Twig?

**Comment by bmuenzenmeyer** [comment]
Not currently, but it is [hiding somewhere in the shadows](https://github.com/pattern-lab/patternlab-node/issues/285) for testing.

@geoffp if I create the repo can you push a 0.0.1 version into it?

**Comment by bmuenzenmeyer** [comment]
@geoffp - https://github.com/pattern-lab/patternengine-node-twig

**Comment by geoffp** [comment]
Yes! I'll do it as soon as I can.

**Comment by bmuenzenmeyer** [comment]
That repo now exists. closing.
