### ISSUE TITLE
Angular Templates

### ISSUE THREAD

**Issue by andybar2** [pattern-lab/edition-node-gulp#64]
Hey guys, how are you? We are working with atomic design concept for all our frontends from some time till now. We are currently testing the edition-node-gulp for pattern-lab, great work by the way! Just wondering.. Is it possible to use Angular templates with it? Or maybe better.. is there an Angular Pattern Engine in your development roadmap to use in place of the default mustache engine?

**Comment by bmuenzenmeyer** [comment]
Thanks for the kind words!

I have no plans for an angular pattern engine, but that shouldn't stop you or anyone else from embarking on their own journey!
