### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by arondius** [pattern-lab/edition-node-gulp#65]
I am using Pattern Lab Node `v1.2.4` on `Mac`, using the `gulp` configuration.
##### Expected Behavior

Running gulp after npm install, I expect gulp to run.
##### Actual Behavior

[16:30:45] Using gulpfile ~/Sites/pattern-library/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
##### Steps to Reproduce

on node 6.2.2 clone repo, run npm install and run Gulp

**Comment by bmuenzenmeyer** [comment]
please report results of `gulp -v` and follow https://github.com/pattern-lab/edition-node-gulp/wiki/Updating-to-Gulp-4 if not on the right version of gulp CLI

**Comment by arondius** [comment]
Yep, upgrading node to v4 did the trick. Thanks :)

**Comment by bmuenzenmeyer** [comment]
Good to hear it!

**Comment by patelvaibhav27** [comment]
I was facing the same issue, and then i came across this github wiki. I followed the steps explained there and it worked for me. Here's the link

https://github.com/pattern-lab/edition-node-gulp/wiki/Updating-to-Gulp-4
