### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by floatingboxes** [pattern-lab/edition-node-gulp#66]
Sorry I'm probably in over my head here, but:

I am using Pattern Lab Node `v1.2.4` on Mac, using the gulp configuration. I just ran `sudo npm install`, worked fine. (Not sure why i'm forced to do `sudo` but anytime i run `npm install` on any project thats the only way to get things installed properly) 

When i run `gulp patternlab:serve` or any other gulp command I get the following:

```
$ gulp patternlab:serve

Loading engines...
...scanning for engines in the core...
- mustache engine: good to go
...scanning for engines in the edition or test directory...
...done loading engines.

[13:17:18] Using gulpfile ~/dev/pd-lab/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:118:18)
    at node.js:952:3

```

Versions:

```
$ node -v
v4.1.2

$ gulp -v
[13:32:42] CLI version 3.8.11
[13:32:42] Local version 4.0.0-alpha.2
```

**Comment by bmuenzenmeyer** [comment]
https://github.com/pattern-lab/edition-node-gulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20cannot%20apply%20

this should help!
