### ISSUE TITLE
`gulp patternlab:build` failing

### ISSUE THREAD

**Issue by mimiflynn** [pattern-lab/edition-node-gulp#67]
I am using Pattern Lab Node- Gulp Edition `v1.2.4` on Mac OS 10.11.5 with Node version 6.2.2.
##### Expected Behavior

Command to `gulp patternlab:build` to build.
##### Actual Behavior

```
$ gulp patternlab:build

Loading engines...
...scanning for engines in the core...
...scanning for engines in the edition or test directory...
- mustache engine: good to go
...done loading engines.

[17:14:15] Using gulpfile ~/Projects/edition-node-gulp-1.2.4/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```
##### Steps to Reproduce

Unzip fresh download of v1.2.4 from the releases page on the project's github page.
`npm install`
`gulp patternlab:build`

**Comment by bmuenzenmeyer** [comment]
https://github.com/pattern-lab/edition-node-gulp/issues/66
https://github.com/pattern-lab/edition-node-gulp/issues/65
https://github.com/pattern-lab/edition-node-gulp/issues/61
https://github.com/pattern-lab/edition-node-gulp/issues/51
