### ISSUE TITLE
Issue installing starterkit

### ISSUE THREAD

**Issue by mimiflynn** [pattern-lab/edition-node-gulp#68]
I am using Pattern Lab Node- Gulp Edition `v1.2.4` on Mac.
##### Expected Behavior

When following directions from [readme.md](https://github.com/pattern-lab/edition-node-gulp#install-a-starterkit) to install a starter kit, starter kit should load successfully.
##### Actual Behavior

Starter kit load does not install and returns an error.
##### Steps to Reproduce

Download a fresh copy of 1.2.4
`npm install`

```
$ npm install pattern-lab/starterkit-mustache-bootstrap --save
edition-node-gulp@1.2.4 /Users/mimiflynn/Projects/edition-node-gulp-1.2.4
└── starterkit-mustache-bootstrap@0.1.0  (git://github.com/pattern-lab/starterkit-mustache-bootstrap.git#1ab9fcfc1f66131aa4534759bd05bb4c265e07f0)
```

```
$ gulp patternlab:loadstarterkit --kit=[starterkit-mustache-bootstrap]

Loading engines...
...scanning for engines in the core...
...scanning for engines in the edition or test directory...
- mustache engine: good to go
...done loading engines.

[10:23:14] Using gulpfile ~/Projects/edition-node-gulp-1.2.4/gulpfile.js
[10:23:14] Starting 'patternlab:loadstarterkit'...
Attempting to load starterkit from /Users/mimiflynn/Projects/edition-node-gulp-1.2.4/node_modules/[starterkit-mustache-bootstrap]/dist
 [starterkit-mustache-bootstrap] not found, please use npm to install it first.
 [starterkit-mustache-bootstrap] not loaded.
```

**Comment by bmuenzenmeyer** [comment]
the square brackets in the documentation are attempting to denote you should replace them and their placeholder contents, so try this again 

$ gulp patternlab:loadstarterkit --kit=starterkit-mustache-bootstrap

**Comment by mimiflynn** [comment]
OMG, how embarrassing.

**Comment by mimiflynn** [comment]
Thanks, btw.

**Comment by bmuenzenmeyer** [comment]
No worries! If it wasn't clear to you it might not be to others who are too shy to report an issue.

I've updated the wiki with a pure example to reflect this conversation https://github.com/pattern-lab/patternlab-node/wiki/Importing-Starterkits
