### ISSUE TITLE
Default outputFileSuffixes don't work with underscore engine

### ISSUE THREAD

**Issue by geoffp** [pattern-lab/edition-node-gulp#69]
I am using Pattern Lab Node- Gulp Edition `v2.3.0` on `Mac`.
##### Expected Behavior

It should work!
##### Actual Behavior

It doesn't.
##### Steps to Reproduce

Install the underscore pattern engine, make some underscore templates in .html, witness breakage.

**Comment by bmuenzenmeyer** [comment]
fixed and pushed
