### ISSUE TITLE
JS files not being watched

### ISSUE THREAD

**Issue by karlschwaier** [pattern-lab/edition-node-gulp#82]
I am using Pattern Lab Node- Gulp Edition `v2.5.1` on `Mac`.
##### Expected Behavior

Watch should detect changes in directory `source/js` and trigger tasks.
##### Actual Behavior

Nothing happens on change.
##### Steps to Reproduce
1. Run `gulp patternlab:watch` or `gulp patternlab:serve`.
2. Edit a file in `source/js` and save it.
3. See on command line that watch process is not reacting.

Watching JS is included in the Grunt Edition (https://github.com/pattern-lab/edition-node-grunt/blob/master/Gruntfile.js#L87-L101) but not in the Gulp Edition (https://github.com/pattern-lab/edition-node-gulp/blob/master/gulpfile.js#L147-L162).

**Comment by alex-page** [comment]
This is quite frustrating when trying to build components that use a simple amount of JS (accordion, carousel, mobile menu). I have added a pull request to fix this exact issue.

**Comment by Frikki** [comment]
This also applies to pattern `*.json` files, though they ought to be watched.
