### ISSUE TITLE
Cannot read property 'length' of undefined - plugins.length() in patternlab-viewer.js

### ISSUE THREAD

**Issue by alex-page** [pattern-lab/edition-node-gulp#91]
I am using Pattern Lab Node- Gulp Edition `v1.3.4` on `Mac`.

##### Expected Behavior
No errors in console on a fresh install.

##### Actual Behavior
Cannot read property 'length' of undefined - plugins.length() in patternlab-viewer.js

##### Steps to Reproduce

1. Download pattern lab gulp edition from the [website](https://github.com/pattern-lab/edition-node-gulp) 
2. Make sure gulp is the correct version following [documentation](https://github.com/pattern-lab/edition-node-gulp/wiki/Updating-to-Gulp-4)
3. Run `gulp patternlab:serve`
4. Open chrome and open http://localhost:3000/
5. View the console for the error.

**Comment by giuseppepaul** [comment]
I'm getting this same error on a Windows machine:

Windows 10
Any browser
Node v6.9.1
Gulp cli v1.2.2

**Comment by giuseppepaul** [comment]
The above change fixes this for me, but you also need to make sure you have a:

`plugins: {}`

in your patternlab-config.js file.

**Comment by alex-page** [comment]
Awesome that worked for me, I assume you meant: `"plugins": {},`

**Comment by bmuenzenmeyer** [comment]
Will be resolved for everyone when https://github.com/pattern-lab/patternlab-node/pull/558 hits a release

**Comment by ba55ie** [comment]
FYI, I have the same error with the Grunt edition. Therefor I think the bug should be fixed in the [styleguidekit-assets-default](https://github.com/pattern-lab/styleguidekit-assets-default) project. Adding a simple check for the (global) variable `plugins` will do the trick.

```
if (!plugins) {
   return;
}
```

https://github.com/pattern-lab/styleguidekit-assets-default/blob/master/src/js/plugin-loader.js#L19

**Comment by bmuenzenmeyer** [comment]
styleguidekit assets default is cross-platform with the PHP version, which is not suffering the issue. The fix I linked to above will resolve this for gulp and grunt node editions. stay tuned
