### ISSUE TITLE
Organize assets into _assets or _content

### ISSUE THREAD

**Issue by ninjasort** [pattern-lab/edition-node-gulp#98]
Hello,

It's not clear at first that the css, images, fonts, js folders are used within the `_patterns` through json files. It's a really great concept, but any way they could be grouped into a `_assets` or `_content` folder which would be consistent with the other folder names? 

This might make it easier to reference the files in the json as well instead of using `../../`. It would look a lot cleaner as well.

<img width="303" alt="screen shot 2017-03-13 at 2 40 15 pm" src="https://cloud.githubusercontent.com/assets/1614348/23869922/24bf7b14-07fb-11e7-864a-8d1f6a829e3b.png">

**Comment by ninjasort** [comment]
Looks like you can set this in the configuration. Didn't see that. https://github.com/pattern-lab/patternlab-node/wiki/Configuration

**Comment by ninjasort** [comment]
Looks like the `npm rune postinstall` adds these files to the root directory when run. Doesn't seem to be listening to the config. Any thoughts?

**Comment by bmuenzenmeyer** [comment]
`postinstall` you refer to is probably adding a starterkit, which adheres to this default structure: https://github.com/pattern-lab/patternlab-node/wiki/Importing-Starterkits

so if you change it, then install a starterkit, it will basically copy them back into location. 

I could see this mechanism being improved in the future to 

- [ ] copy to what the user has mapped
- [ ] not automatically install starterkits in `postinstall`

that second point is being addressed as part of 3.0 work
